/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente.Vistas;

import javax.swing.JFileChooser;
import Cliente.Controladores.Controlador;
import Modelos.Libro;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Luis
 */
public class InternalAddBook extends javax.swing.JInternalFrame {
    Controlador controlador_cliente;
    private int numeroPaginas;
    private ArrayList contenido;
    private ImageIcon portada;
            
    /**
     * Creates new form InternalAddBoo
     */
    public InternalAddBook(Controlador controlador_cliente){
        this.controlador_cliente = controlador_cliente;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        buttonAgregar = new javax.swing.JButton();
        fieldTitulo = new javax.swing.JTextField();
        fieldAutor = new javax.swing.JTextField();
        fieldIsbn = new javax.swing.JTextField();
        comboCategoria = new javax.swing.JComboBox<>();
        checkBestSeller = new javax.swing.JCheckBox();
        fieldPrecio = new javax.swing.JTextField();
        comboCalificacion = new javax.swing.JComboBox<>();
        fieldEdad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        paneResumen = new javax.swing.JTextPane();
        buttonContenido = new javax.swing.JButton();
        buttonPortada = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Agregar libro");

        jLabel1.setText("Titulo");

        jLabel2.setText("Autor");

        jLabel3.setText("ISBN");

        jLabel5.setText("Categoria");

        jLabel7.setText("Precio");

        jLabel8.setText("Calificacion");

        jLabel9.setText("Resumen");

        jLabel10.setText("Edad minima");

        jLabel11.setText("Contenido");

        jLabel12.setText("Portada");

        buttonAgregar.setText("Agregar");
        buttonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarActionPerformed(evt);
            }
        });

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Romance", "Suspenso", "Terror", "Drama", "Matematicas", "Fisica", "Estadistica", "Programacion", " " }));

        checkBestSeller.setText("Best Seller");

        comboCalificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jScrollPane1.setViewportView(paneResumen);

        buttonContenido.setText("Seleccionar contenido");
        buttonContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonContenidoActionPerformed(evt);
            }
        });

        buttonPortada.setText("Seleccionar portada");
        buttonPortada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPortadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAgregar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkBestSeller)
                            .addComponent(fieldTitulo)
                            .addComponent(fieldAutor)
                            .addComponent(fieldIsbn)
                            .addComponent(comboCategoria, 0, 155, Short.MAX_VALUE)
                            .addComponent(fieldPrecio)
                            .addComponent(comboCalificacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldEdad)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonPortada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBestSeller)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(buttonContenido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(buttonPortada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAgregar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean validarCampos(){ 
         
        if(fieldTitulo.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Debe ingresar un Titulo");
            return false;
        }
         
        if(fieldAutor.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Debe ingresar un Autor");
            return false;
        }
         
        if (fieldIsbn.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Debe ingresar un ISBN");
            return false;
        }
        
        if(comboCategoria.getSelectedItem() == null)
        {
            JOptionPane.showMessageDialog(null,"Debe seleccionar una categoria");
            return false;
        }
            
        if(fieldPrecio.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Debe ingresar un Precio");
            return false;
        }
        
        if(comboCalificacion.getSelectedItem()== null)
        {
            JOptionPane.showMessageDialog(null,"Debe seleccionar una calificacion");
            return false;
        }
        
        if(fieldEdad.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Debe ingresar una Edad");
            return false;
        }
        
        if(paneResumen.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Debe ingresar un Resumen");
            return false;
        }
        

        return true;
    }  
    private void buttonContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonContenidoActionPerformed
     
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(this);
        String path = fileChooser.getSelectedFile().getAbsolutePath();
        //ArrayList texto = controlador_cliente.seleccionarTexto(path);
        //numeroPaginas = (int)texto.get(1);
        //contenido = controlador_cliente.seleccionarTexto(path);
        
    }//GEN-LAST:event_buttonContenidoActionPerformed

    private void buttonPortadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPortadaActionPerformed
       
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(this);
        String path = fileChooser.getSelectedFile().getAbsolutePath();
       // portada = controlador_cliente.seleccionarPortada(path);
        
    }//GEN-LAST:event_buttonPortadaActionPerformed

    private void buttonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarActionPerformed
        try{
            if(validarCampos())
            {
            Libro libro = new Libro();
            libro.setIsbn(this.fieldIsbn.getText());
            libro.setTitulo(this.fieldTitulo.getText());
            libro.setResumen(this.paneResumen.getText());
            libro.setAutor(this.fieldAutor.getText());
            libro.setPrecio(Double.parseDouble(this.fieldPrecio.getText()));
            libro.setCategoria((String)this.comboCategoria.getSelectedItem());
            libro.setBestSeller(this.checkBestSeller.isSelected());
            libro.setEdadMinima(Integer.parseInt(this.fieldEdad.getText()));
            libro.setCalificacion(Integer.parseInt((String)this.comboCalificacion.getSelectedItem()));
            
            ArrayList response = controlador_cliente.agregarLibro(libro);
            JOptionPane.showMessageDialog(this, response);   
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Asegurese de que los campos esten correctamente diligenciados", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_buttonAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgregar;
    private javax.swing.JButton buttonContenido;
    private javax.swing.JButton buttonPortada;
    private javax.swing.JCheckBox checkBestSeller;
    private javax.swing.JComboBox<String> comboCalificacion;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JTextField fieldAutor;
    private javax.swing.JTextField fieldEdad;
    private javax.swing.JTextField fieldIsbn;
    private javax.swing.JTextField fieldPrecio;
    private javax.swing.JTextField fieldTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane paneResumen;
    // End of variables declaration//GEN-END:variables
}
