/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente.Vistas;

import Cliente.Controladores.Controlador;
import Modelos.Libro;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;
import javax.swing.text.Highlighter.HighlightPainter;

/**
 *
 * @author Steven
 */
public class InternalVistaLectura extends javax.swing.JInternalFrame {
    private Controlador controlador_cliente;
    
    private Libro libro;
    private int pagina_actual = 0;
    /**
     * Creates new form InternalVistaLectura
     */
    public InternalVistaLectura(Controlador controlador_cliente) {
        initComponents();
        
        TextAreaLibro.setSize(400,400);
        TextAreaLibro.setLineWrap(true);
        TextAreaLibro.setEditable(false);
        TextAreaLibro.setVisible(true);
        jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        
        this.controlador_cliente = controlador_cliente;
        cargarInformacion();
    }
    
    public void cargarInformacion(){
        
        String contenidoEjemplo = Libro.contenidoLibroEjemplo(); 
        libro = new Libro();
        libro.setContenido(contenidoEjemplo);
        libro.setIsbn("1234");
        libro.setTitulo("La Flaqueza del Bolchevique");
        libro.setResumen("bduibdibfubcbcjidbcyfbcfjnurfncjfnvfubfnvjfnvfubvfijne");
        libro.setAutor("Pepito Perez");
        libro.setPrecio(50);
        libro.setCategoria("Romance");
        libro.setBestSeller(true);
        libro.setEdadMinima(10);
        libro.setCalificacion(5);
        
        this.LabelTituloLibro.setText(libro.getTitulo());
        this.TextAreaLibro.setText((String)libro.getPaginas().get(pagina_actual)); 
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonResaltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaLibro = new javax.swing.JTextArea();
        ButtonAgregarNota = new javax.swing.JButton();
        LabelTamañoLetra = new javax.swing.JLabel();
        ComboColorFondo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        LabelTituloLibro = new javax.swing.JLabel();
        ComboTamañoLetra = new javax.swing.JComboBox<>();
        ComboColorLetra = new javax.swing.JComboBox<>();
        ComboFuenteLetra = new javax.swing.JComboBox<>();
        LabelColorLetra = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ButtonPagAnterior = new javax.swing.JButton();
        FieldNumeroPagina = new javax.swing.JTextField();
        ButtonPagSiguiente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaNotas = new javax.swing.JTextArea();

        ButtonResaltar.setText("Resaltar");
        ButtonResaltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResaltarActionPerformed(evt);
            }
        });

        TextAreaLibro.setColumns(20);
        TextAreaLibro.setRows(5);
        TextAreaLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TextAreaLibroMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TextAreaLibro);

        ButtonAgregarNota.setText("Agregar Nota");
        ButtonAgregarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarNotaActionPerformed(evt);
            }
        });

        LabelTamañoLetra.setText("Tamaño Letra");

        ComboColorFondo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Gris", "Negro" }));
        ComboColorFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboColorFondoActionPerformed(evt);
            }
        });

        jLabel1.setText("Color Fondo");

        LabelTituloLibro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelTituloLibro.setText("Titulo Libro");

        ComboTamañoLetra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "14", "16", "24" }));
        ComboTamañoLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboTamañoLetraActionPerformed(evt);
            }
        });

        ComboColorLetra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro ", "Blanco ", "Gris" }));
        ComboColorLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboColorLetraActionPerformed(evt);
            }
        });

        ComboFuenteLetra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Times New Roman", "Arial", "Calibri" }));
        ComboFuenteLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboFuenteLetraActionPerformed(evt);
            }
        });

        LabelColorLetra.setText("Color Letra");

        jLabel2.setText("Fuente Letra");

        ButtonPagAnterior.setText("Pagina Anterior");
        ButtonPagAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPagAnteriorActionPerformed(evt);
            }
        });

        ButtonPagSiguiente.setText("Siguiente Pagina");
        ButtonPagSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPagSiguienteActionPerformed(evt);
            }
        });

        TextAreaNotas.setColumns(20);
        TextAreaNotas.setRows(5);
        jScrollPane2.setViewportView(TextAreaNotas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelTituloLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(187, 187, 187))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelTamañoLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboTamañoLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(ComboFuenteLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelColorLetra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ComboColorLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ButtonAgregarNota, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(ButtonResaltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(25, 25, 25))))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(ButtonPagAnterior)
                .addGap(26, 26, 26)
                .addComponent(FieldNumeroPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonPagSiguiente)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(ComboColorFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(LabelTituloLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonAgregarNota)
                        .addGap(32, 32, 32)
                        .addComponent(ButtonResaltar)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonPagAnterior)
                    .addComponent(FieldNumeroPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPagSiguiente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTamañoLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(LabelColorLetra)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboTamañoLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboColorFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboFuenteLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboColorLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonResaltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResaltarActionPerformed
        // TODO add your handling code here:
        if (TextAreaLibro.getSelectedText() != null) { // See if they selected something 
            String selected_text = TextAreaLibro.getSelectedText();
            //JOptionPane.showMessageDialog(null, selected_text);
            
            Highlighter highlighter = TextAreaLibro.getHighlighter();
            HighlightPainter painter = new DefaultHighlighter.DefaultHighlightPainter(Color.yellow);
            int p0 = this.TextAreaLibro.getText().indexOf(selected_text);
            int p1 = p0 + selected_text.length();
            try {
                highlighter.addHighlight(p0, p1, painter );
            } catch (BadLocationException ex) {
                Logger.getLogger(InternalVistaLectura.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ButtonResaltarActionPerformed

    private void ComboColorFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboColorFondoActionPerformed
        // TODO add your handling code here:
        switch ((String)ComboColorFondo.getSelectedItem()){
            case "Blanco":
                TextAreaLibro.setBackground(Color.white);
                break;
            case "Gris": 
                TextAreaLibro.setBackground(Color.gray);
                break; 
            case "Negro": 
                TextAreaLibro.setBackground(Color.black);
                break; 
        }
    }//GEN-LAST:event_ComboColorFondoActionPerformed

    private void ComboTamañoLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboTamañoLetraActionPerformed
        // TODO add your handling code here:     
        TextAreaLibro.setFont( new Font("Dialog", Font.ROMAN_BASELINE, Integer.parseInt((String)ComboTamañoLetra.getSelectedItem())) ); 
    }//GEN-LAST:event_ComboTamañoLetraActionPerformed

    private void TextAreaLibroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextAreaLibroMouseReleased
        
    }//GEN-LAST:event_TextAreaLibroMouseReleased

    private void ComboColorLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboColorLetraActionPerformed
        // TODO add your handling code here:
        switch ((String)ComboColorLetra.getSelectedItem()){
            case "Blanco":
                TextAreaLibro.setForeground(Color.white);
                break;
            case "Gris": 
                TextAreaLibro.setForeground(Color.gray);
                break; 
            case "Negro": 
                TextAreaLibro.setForeground(Color.black);
                break; 
        }
    }//GEN-LAST:event_ComboColorLetraActionPerformed

    private void ComboFuenteLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboFuenteLetraActionPerformed
        // TODO add your handling code here
        switch ((String)ComboFuenteLetra.getSelectedItem()){
            case "Times New Roman": 
                TextAreaLibro.setFont( new Font("Times New Roman", Font.ROMAN_BASELINE, Integer.parseInt((String)ComboTamañoLetra.getSelectedItem())) ); 
                break;
            case "Arial": 
                TextAreaLibro.setFont( new Font("Arial", Font.ROMAN_BASELINE, Integer.parseInt((String)ComboTamañoLetra.getSelectedItem())) ); 
                break; 
            case "Calibri": 
                TextAreaLibro.setFont( new Font("Calibri", Font.ROMAN_BASELINE, Integer.parseInt((String)ComboTamañoLetra.getSelectedItem())) ); 
                break; 
        }
    }//GEN-LAST:event_ComboFuenteLetraActionPerformed

    private void mostrarPagina(){
        try{
            this.TextAreaLibro.setText((String)libro.getPaginas().get(this.pagina_actual)); 
            this.FieldNumeroPagina.setText(Integer.toString(this.pagina_actual));
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "No hay paginas");
        }
    }
    
    private void ButtonPagAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPagAnteriorActionPerformed
        // TODO add your handling code here:S
        this.pagina_actual = this.pagina_actual-1;
        mostrarPagina();
    }//GEN-LAST:event_ButtonPagAnteriorActionPerformed

    
    
    private void ButtonPagSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPagSiguienteActionPerformed
        this.pagina_actual = this.pagina_actual+1;
        mostrarPagina();
    }//GEN-LAST:event_ButtonPagSiguienteActionPerformed

    private void ButtonAgregarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarNotaActionPerformed
        // TODO add your handling code here:
        libro.agregarNota(pagina_actual, this.TextAreaNotas.getText());
        JOptionPane.showMessageDialog(null, "El libro: " + libro.getNotas()[1][0]); 
    }//GEN-LAST:event_ButtonAgregarNotaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAgregarNota;
    private javax.swing.JButton ButtonPagAnterior;
    private javax.swing.JButton ButtonPagSiguiente;
    private javax.swing.JButton ButtonResaltar;
    private javax.swing.JComboBox<String> ComboColorFondo;
    private javax.swing.JComboBox<String> ComboColorLetra;
    private javax.swing.JComboBox<String> ComboFuenteLetra;
    private javax.swing.JComboBox<String> ComboTamañoLetra;
    private javax.swing.JTextField FieldNumeroPagina;
    private javax.swing.JLabel LabelColorLetra;
    private javax.swing.JLabel LabelTamañoLetra;
    private javax.swing.JLabel LabelTituloLibro;
    private javax.swing.JTextArea TextAreaLibro;
    private javax.swing.JTextArea TextAreaNotas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
